#测试下创建一个不知道什么东西，看看效果什么样子
21可以还有很多行
123监考老师缴费
sadf	
	1的                      

import sys
import you_get
from multiprocessing import Pool
#url ='你要下载的视频链接'
#path='你要把视频保存到哪里'
url = 'https://www.bilibili.com/video/BV1dt411d7uP?spm_id_from=333.1007.top_right_bar_window_history.content.click&vd_source=729e9a2ee9a03db7a1a4f868f98ba92c&t=9.4' 
path = '/mysearch'
total=14

def down1():
    start_url = url
    path1 = path
    for i in range(1, 3, 1):
        url1 = start_url + str(i)
        download(url1, path1)


def down2():
    start_url = url
    path1 = path
    for i in range(3, 5, 1):
        url1 = start_url + str(i)
        download(url1, path1)


def down3():
    start_url = url
    path1 = path
    for i in range(5, 7, 1):
        url1 = start_url + str(i)
        download(url1, path1)


def down4():
    start_url = url
    path1 = path
    for i in range(7, 9, 1):
        url1 = start_url + str(i)
        download(url1, path1)


def down5():
    start_url = url
    path1 = path
    for i in range(9, 11, 1):
        url1 = start_url + str(i)
        download(url1, path1)


def down6():
    start_url = url
    path1 = path
    for i in range(11, 13, 1):
        url1 = start_url + str(i)
        download(url1, path1)


def down7():
    start_url = url
    path1 = path
    for i in range(13, 15, 1):
        url1 = start_url + str(i)
        download(url1, path1)


def down8():
    start_url = url
    path1 = path
    for i in range(35, 40, 1):
        url1 = start_url + str(i)
        download(url1, path1)


def download(url, path):
    sys.argv = ['you-get', '-o', path, url]
    you_get.main()


def main():
    po = Pool(8)


    po.apply_async(down1)
    po.apply_async(down2)
    po.apply_async(down3)
    po.apply_async(down4)
    po.apply_async(down5)
    po.apply_async(down6)
    po.apply_async(down7)
    po.apply_async(down8)
    po.close()
    po.join()


if __name__ == '__main__':
    main()
